remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "contrast"
locale: "en-US"
title: "The Hyphal Tip"
title_separator: "|"
subtitle: "Digesting the Fungal genomes"
name: "Jason Stajich"
description: "Fungal genomics"
url: https://fungalgenomes.org
#baseurl: /blog
repository: "hyphaltip/fungalgenomes.org"
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
header:
  teaser: /assets/header/cropped-burned11.jpg
