source "https://rubygems.org"

# jekyll
gem "jekyll"

# plugins
group :jekyll_plugins do
  gem "jekyll-redirect-from"
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-include-cache"

  # other potentially useful plugins
  gem "jekyll-github-metadata"
  gem 'jekyll-avatar'
  gem 'jekyll-gist'
  gem 'jekyll-mentions'
  gem 'jekyll-relative-links'
  gem 'jemoji'
end

gem "webrick", "~> 1.7"
